### ISSUE TITLE
zref doesn't work with include files

### ISSUE THREAD

**Issue by onatt** [ho-tex/zref#14]
The following very simple LaTeX-document produces the error `No counter 'zref@unique' defined.` where `filename.tex` ist just an empty file.

```
\documentclass{article}
\usepackage{zref}
\begin{document}
\include{filename}
\end{document}
```

I am using latest version of texlive (2022) which includes zref (2022-03-08 v2.33). The error does not occur with texlive 2021 which includes zref (Version: 2020-07-03 v2.32). Of course, the problem can be fixed by adding `\newcounter{zref@unique}` but this should not be necessary. The problem seems to be related to issue #10 which should have been fixed in v2.33.

**Comment by u-fischer** [comment]
hm right. The counter is only in the zref-perpage module. I will adjust. For now load the module too.

**Comment by onatt** [comment]
> hm right. The counter is only in the zref-perpage module. I will adjust. For now load the module too.

Great, thanks a lot. I am looking forward to the new version of zref. The example given above is actually the result of backtracking the same error that occurs when using the package `mdframed` which depends on `zref`.

Best regards
Oliver
