### ISSUE TITLE
zref-counter is incompatible with hyperref

### ISSUE THREAD

**Issue by u-fischer** [ho-tex/zref#5]
~~~~
\documentclass{article}

\usepackage{zref-counter}
\usepackage{zref-user}

\usepackage{hyperref}
\begin{document}
\refstepcounter{equation}\zlabel{eq1}

\refstepcounter{section}
\begin{equation}\zlabel{eq2}
  1=1
\end{equation}
\end{document}
~~~~

In this document, the second counter is reported as `section`:

~~~~
\zref@newlabel{eq1}{\default{1}\page{1}\counter{equation}}
\zref@newlabel{eq2}{\default{2}\page{1}\counter{section}}
~~~~

The source of the problem is that zref-counter patches \refstepcounter at begin document. But at this time hyperref has already moved \refstepcounter around and patched various commands (e.g. equation) to use variations. This lines are e.g. all from hyperref:

~~~~
\let\new@refstepcounter\refstepcounter
\let\refstepcounter\H@refstepcounter
\let\refstepcounter\new@refstepcounter
\H@refstepcounter
\let\H@refstepcounter\refstepcounter
\let\Hy@saved@refstepcounter\refstepcounter
\hyper@refstepcounter
\ifx\refstepcounter\Hy@varioref@refstepcounter
~~~~

One way to solve the problem would be if zref-counter would patch \refstepcounter directly. 

A perhaps safer way would be to patch stepcounter instead:

~~~
\makeatletter
  \ZREF@patch{stepcounter}{%
    \def\stepcounter#1{%
      \zref@setcurrent{counter}{#1}%
      \ZREF@org@stepcounter{#1}%
    }%
  }%
\makeatother
~~~

It would give a different result then currently for `\refstepcounter{section}\stepcounter{someothercounter}\zlabel{blub}`. But this is perhaps not really a problem.  

The best would probably be if latex itself would record which counter has just been advanced by stepcounter and refstepcounter ...

**Comment by jenbotello** [comment]
> ```
> \documentclass{article}
> 
> \usepackage{zref-counter}
> \usepackage{zref-user}
> 
> \usepackage{hyperref}
> \begin{document}
> \refstepcounter{equation}\zlabel{eq1}
> 
> \refstepcounter{section}
> \begin{equation}\zlabel{eq2}
>   1=1
> \end{equation}
> \end{document}
> ```
> 
> 
> In this document, the second counter is reported as `section`:
> 
> 
> ```
> \zref@newlabel{eq1}{\default{1}\page{1}\counter{equation}}
> \zref@newlabel{eq2}{\default{2}\page{1}\counter{section}}
> ```
> 
> 
> The source of the problem is that zref-counter patches \refstepcounter at begin document. But at this time hyperref has already moved \refstepcounter around and patched various commands (e.g. equation) to use variations. This lines are e.g. all from hyperref:
> 
> 
> ```
> \let\new@refstepcounter\refstepcounter
> \let\refstepcounter\H@refstepcounter
> \let\refstepcounter\new@refstepcounter
> \H@refstepcounter
> \let\H@refstepcounter\refstepcounter
> \let\Hy@saved@refstepcounter\refstepcounter
> \hyper@refstepcounter
> \ifx\refstepcounter\Hy@varioref@refstepcounter
> ```
> 
> 
> One way to solve the problem would be if zref-counter would patch \refstepcounter directly.
> 
> 
> A perhaps safer way would be to patch stepcounter instead:
> 
> 
> ```
> \makeatletter
>   \ZREF@patch{stepcounter}{%
>     \def\stepcounter#1{%
>       \zref@setcurrent{counter}{#1}%
>       \ZREF@org@stepcounter{#1}%
>     }%
>   }%
> \makeatother
> ```
> 
> 
> It would give a different result then currently for `\refstepcounter{section}\stepcounter{someothercounter}\zlabel{blub}`. But this is perhaps not really a problem.
> 
> 
> The best would probably be if latex itself would record which counter has just been advanced by stepcounter and refstepcounter ...

**Comment by u-fischer** [comment]
@jenbotello sorry? why do you simply copy my post?

**Comment by u-fischer** [comment]
A fix for LaTeX2e <2020-10-01> pre-release-6 or newer has been uploaded to ctan.
