### ISSUE TITLE
Cannot use external files with aux extension

### ISSUE THREAD

**Issue by ianhbell** [ho-tex/zref#7]
I am trying to use zref to keep my supporting information reference numbers in sync with my main manuscript, and this works absolutely beautifully when I am working on my own on my computer.  But when submitting my manuscript (specifically to AIP), they don't allow .aux files in the editorial system.  I have wracked my brain trying to find a solution, but it seems that I have hit a wall.  Short of hacking zref, is there any facility for changing the file extension of the file to be read?  It seems not. I thought maybe it was the ext flag, but that's not it either.

**Comment by u-fischer** [comment]
Assuming that you are speaking of the zref-xr module and the `\zexternaldocument` command: no there is nothing to exchange the extension aux, this is hard coded as it is the standard extension for the aux-file in latex. You will either have to patch `\ZREF@xr@externaldocument`, or add your external aux with the filecontents environment to your main file, then it is created at compilation time - the system can't complain about this, as the standard aux is then created too.

**Comment by ianhbell** [comment]
Aha -- filecontents is the solution I hope.  I'll give that a shot today.  Thanks for responding so quickly.

**Comment by ianhbell** [comment]
After a few additional hoops, I got the filecontents approach working, thanks again.
