### ISSUE TITLE
zref-pagelayout/zref-abspos packages compilation error (LaTeX 2020-10-01)

### ISSUE THREAD

**Issue by ejazzfr** [ho-tex/zref#8]
Since a recent TeXLive update (LaTeX kernel 2020-10-01), the following compilation error occurs, just loading the `zref-pagelayout' package:

    ! Undefined control sequence.
    \Z@C@outputboxwd ->\AtBeginShipoutBoxWidth 
     ! Undefined control sequence.
    \Z@C@outputboxht ->\AtBeginShipoutBoxHeight 
    ! Undefined control sequence.
    \Z@C@outputboxdp ->\AtBeginShipoutBoxDepth 

PS: A question has been posted at TeX.SX [zref-pagelayout/zref-abspos packages compilation error](https://tex.stackexchange.com/questions/566048/zref-pagelayout-zref-abspos-packages-compilation-error)
 
MWE:

    \documentclass[10pt]{article}
    \usepackage[a4paper,margin=1in]{geometry}
    %\usepackage{zref-abspos}% Compilation error (loads zref-pagelayout)
    \usepackage{zref-pagelayout}% Compilation error

    \begin{document}

    \section{Test}

    Where is the issue? From an incompatibility with the new LaTeX kernel (2020-10-01)?

    \end{document}

**Comment by u-fischer** [comment]
I just fixed this in https://github.com/ho-tex/zref/commit/698664a4b47c6a1821b682f067328ddef83e6769 and uploaded to ctan
