### ISSUE TITLE
\ProvidesPackage date invalid

### ISSUE THREAD

**Issue by FOCCOF** [ho-tex/zref#9]
The package says :

\ProvidesPackage{zref}
  [2020-07-03 v2.32 A new reference scheme for LaTeX (HO)]%

But the standard parsing macro from LaTeX require the date format :

  2020/07/03 v2.32

Thank you, and enjoy a merry christmas.

**Comment by davidcarlisle** [comment]
LaTeX has supported  `-` in dates for almost four years

```
2017-03-08  David Carlisle  <latex-bugs@latex-project.org>

	* ltclass.dtx, latexrelease.ins: support yyyy-mm-dd format
	in addition to yyyy/mm/dd

```

So unless you have an example where this is failing, I don't see any issue here?

**Comment by FOCCOF** [comment]
The problem comes from ltxcmds.sty indeed.

It is documented here : https://github.com/ho-tex/ltxcmds/issues/2

Thanks for your reply.
